# Generated by Django 5.1.6 on 2025-04-06 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Логин"
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Пароль"
                    ),
                ),
                ("firstName", models.CharField(max_length=150, verbose_name="Имя")),
                ("lastName", models.CharField(max_length=150, verbose_name="Фамилия")),
                (
                    "middleName",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отчество"
                    ),
                ),
                ("grade", models.CharField(max_length=10, verbose_name="Класс")),
                ("index", models.CharField(max_length=5, verbose_name="Индекс класса")),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Предмет"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Ученик")],
                        default="student",
                        max_length=10,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "auth_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "about",
                    models.TextField(blank=True, null=True, verbose_name="О себе"),
                ),
                (
                    "contacts",
                    models.JSONField(blank=True, default=dict, verbose_name="Контакты"),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="enrolled_students",
                        through="subjects.SubjectEnrollment",
                        to="subjects.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
            },
        ),
    ]
