# Generated by Django 5.1.6 on 2025-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='role',
            field=models.CharField(default='student', max_length=10, verbose_name='Роль'),
        ),
    ]
