# Generated by Django 5.1.6 on 2025-03-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuser",
            name="auth_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
