# Generated by Django 5.1.6 on 2025-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='index',
            field=models.CharField(default='А', max_length=5, verbose_name='Индекс класса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='grade',
            field=models.CharField(max_length=10, verbose_name='Класс'),
        ),
    ]
