# Generated by Django 5.1.6 on 2025-03-24 17:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users_student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="studentuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
