# Generated by Django 5.1.6 on 2025-03-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_student", "0002_studentuser_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentuser",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="studentuser",
            name="contacts",
            field=models.JSONField(blank=True, default=dict, verbose_name="Контакты"),
        ),
    ]
