# Generated by Django 5.1.6 on 2025-03-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_student", "0003_studentuser_about_studentuser_contacts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentuser",
            name="auth_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
