# Generated by Django 5.1.6 on 2025-03-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_student', '0004_alter_studentuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='user',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Логин'),
        ),
    ]
