# Generated by Django 5.1.6 on 2025-04-06 19:15

import django.db.models.deletion
import materials.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file",
                    models.FileField(
                        upload_to=materials.models.student_material_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Документ"),
                            ("video", "Видео"),
                            ("presentation", "Презентация"),
                            ("other", "Другое"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="Тип материала",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(default=False, verbose_name="Просмотрено"),
                ),
                (
                    "is_student_material",
                    models.BooleanField(
                        default=False, verbose_name="Загружено учеником"
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Предмет"
                    ),
                ),
            ],
            options={
                "db_table": "student_materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("document", "Документ"),
                            ("video", "Видео"),
                            ("presentation", "Презентация"),
                            ("link", "Внешняя ссылка"),
                        ],
                        max_length=20,
                        verbose_name="Тип материала",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Внешняя ссылка"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_materials",
                        related_query_name="material",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный материал",
                "verbose_name_plural": "Учебные материалы",
                "db_table": "materials",
                "ordering": ["-created_at"],
            },
        ),
    ]
