# Generated by Django 5.1.6 on 2025-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaterial',
            name='is_student_material',
            field=models.BooleanField(default=False, verbose_name='Загружено студентом'),
        ),
    ]
