# Generated by Django 5.1.6 on 2025-04-06 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        ("subjects", "0001_initial"),
        ("users_student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="subjects.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="studentmaterial",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_student_materials",
                related_query_name="student_material",
                to="users_student.studentuser",
            ),
        ),
        migrations.AddField(
            model_name="studentmaterial",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_materials",
                to="users_student.studentuser",
            ),
        ),
    ]
