# Generated by Django 5.1.6 on 2025-04-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmaterial",
            name="subject_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Предмет"
            ),
        ),
    ]
