# Generated by Django 5.1.6 on 2025-03-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_material_created_by_studentmaterial"),
        ("users_student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("document", "Документ"),
                    ("video", "Видео"),
                    ("presentation", "Презентация"),
                    ("other", "Другое"),
                ],
                default="document",
                max_length=20,
                verbose_name="Тип материала",
            ),
        ),
        migrations.AlterField(
            model_name="studentmaterial",
            name="file",
            field=models.FileField(
                upload_to="student_materials/%Y/%m/%d/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="studentmaterial",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_materials",
                to="users_student.studentuser",
            ),
        ),
    ]
