# Generated by Django 5.1.6 on 2025-04-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_studentmaterial_is_student_material'),
        ('users_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmaterial',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_student_materials', related_query_name='student_material', to='users_student.studentuser'),
        ),
    ]
