# Generated by Django 5.1.6 on 2025-03-01 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('school_name', models.CharField(blank=True, default='', max_length=200)),
                ('about', models.TextField(blank=True, default='')),
                ('telegram', models.CharField(blank=True, default='', max_length=100)),
                ('viber', models.CharField(blank=True, default='', max_length=100)),
                ('specialization', models.CharField(blank=True, default='', max_length=200)),
                ('contacts', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
            },
        ),
    ]
