# Generated by Django 5.1.6 on 2025-02-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='viber',
            field=models.CharField(blank=True, max_length=100, verbose_name='Viber'),
        ),
    ]
