# Generated by Django 5.1.6 on 2025-03-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheruser',
            name='middle_name',
        ),
    ]
