# Generated by Django 5.1.6 on 2025-02-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_teacher', '0003_alter_teacheruser_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacheruser',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacheruser',
            name='viber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
