# Generated by Django 5.1.6 on 2025-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_teacher', '0004_alter_teacheruser_options_alter_teacheruser_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='contacts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacheruser',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
