# Generated by Django 5.1.6 on 2025-04-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_type', models.CharField(choices=[('super_admin', 'Суперадминистратор'), ('admin_teacher', 'Администратор-учитель')], max_length=20, verbose_name='Тип администратора')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Суперадминистратор')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
    ]
