# Generated by Django 5.1.6 on 2025-02-26 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', 'XXXX_alter_subject_code_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubject',
            options={'verbose_name': 'Назначение учителя', 'verbose_name_plural': 'Назначения учителя'},
        ),
        migrations.AddField(
            model_name='subject',
            name='index',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Индекс класса'),
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
    ]
