# Generated by Django 5.1.6 on 2025-02-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_alter_teachersubject_options_subject_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Код предмета'),
        ),
    ]
