# Generated by Django 5.1.6 on 2025-04-06 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        ("users_student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_enrollments",
                to="users_student.studentuser",
                verbose_name="Ученик",
            ),
        ),
        migrations.AddField(
            model_name="subjectenrollment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="subjects.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="subjects.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AddField(
            model_name="teachersubject",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_subjects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Учитель",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectenrollment",
            unique_together={("subject", "student")},
        ),
    ]
