# Generated by Django 5.1.6 on 2025-04-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("due_date", models.DateTimeField(verbose_name="Срок сдачи")),
                (
                    "max_score",
                    models.PositiveIntegerField(verbose_name="Максимальный балл"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
                "db_table": "assignments",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата отправки"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="submissions/",
                        verbose_name="Файл",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Оценка"
                    ),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="Отзыв учителя"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата оценки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на задание",
                "verbose_name_plural": "Ответы на задания",
                "db_table": "assignment_submissions",
            },
        ),
    ]
